### PR TITLE
Add admin inlines

### PR DESCRIPTION
**Pull request by DeeeeLAN**
## Description

- Added inlines for the tables in the admin interface
  - I modeled the column choices based on the Paddle.com versions of the same tables where possible
- Added typing to model functions
- Migrated all `print` functions to use `logger.info` instead
- Made `account_id` optional when receiving a subscription webhook event
- Fixed address admin item crashing when opened
- Fixed address.customer not getting attached on address webhook event
- Add Discount model
- Lots of various codestyle cleanup

## Related Issue

#70 

## Type of Change

- [ ] 📚 Examples / docs / tutorials / dependencies update
- [x] 🔧 Bug fix (non-breaking change which fixes an issue)
- [x] 🥂 Improvement (non-breaking change which improves an existing feature)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

## Checklist

- [x] I've read the [`CODE_OF_CONDUCT.md`](https://github.com/websideproject/paddle-billing-client/blob/main/CODE_OF_CONDUCT.md) document.
- [x] I've read the [`CONTRIBUTING.md`](https://github.com/websideproject/paddle-billing-client/blob/main/CONTRIBUTING.md) guide.
- [x] I've updated the code style using `make codestyle`.
- [ ] I've written tests for all new methods and classes that I created.
- [ ] I've written the docstring in Google format for all the methods and classes that I used.

### CODE REVIEW

**Comment by DeeeeLAN** [comment]
I added a second commit that removed the Account model dependency. I don't see the value in using Account in parallel with AUTH_USER_MODEL, especially when the default for Account is to use the user model anyway. I think it would be better to just keep it all within the user model and not create a layer of abstraction.

**Comment by bgervan** [comment]
The account model is required for flexibility. In a multitenant system, 1 user can have multiple workspace and with this multiple subscription for the same product.

**Comment by DeeeeLAN** [comment]
I see, that makes sense. I will add that part back in then.

**Comment by DeeeeLAN** [comment]
I modified `from_paddle_data` to allow `account_id` to be optional. If it is supplied and the account model doesn't exist, it returns an error still, but if it is not supplied it will just leave the field null.

**Comment by bgervan** [comment]
Please check this comment https://github.com/websideproject/django-paddle-billing/issues/70#issuecomment-2143297164

Can you describe your workflow from the frontend? How do you plan linking customer to users and subscriptions to users/accounts? (Js example code? )

Making the account optional doesn't break stuff for the users who uses the account_id, but can create orphan customers and subscriptions for the others

**Comment by DeeeeLAN** [comment]
In my case, each user will only be allowed one subscription at a time and I require an account to be created before signing up, so I have their email. However, I am not sure how I will handle third-party sign-in cases with no email yet. 

I just created a new user account and registered for a subscription on my site and I see in the webhooks the paddle customer get created then the subscription with the customer_id attached, so I am able to get them all linked up to the email address provided by the user when they subscribe. In my case at least, I am not seeing any risk of an orphaned account or subscription.

**Comment by bgervan** [comment]
This PR started to grow big from the original title. It's ok for now, but let's create other PRs for other than fixes of the current PR scope. 

I need some time to review and test the changes

**Comment by DeeeeLAN** [comment]
No worries. I actually intended to make them separate pull requests but I wasn't paying attention and just ran with it when I noticed.

**Pull request merged**
